version: "3.8"

services:

  apache:
    container_name: apache_2.4
    working_dir: /srv/http/parking-system
    build:
      context: .devops/apache
    volumes:
      - ./src/:/srv/http/parking-system
    ports:
      - 80:80

  php:
    container_name: php_8.2
    working_dir: /srv/http/parking-system
    build:
      context: .devops/php
    volumes:
      - ./src/:/srv/http/parking-system

  mysql:
    container_name: mysql_8.1
    build:
      context: .devops/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_system
      MYSQL_USER: ps_backend_user
      MYSQL_PASSWORD: ps_backend_user_password

volumes:
  mysql: