version: "3.8"

services:

  apache:
    container_name: apache_2.4
    build:
      context: .devops
      dockerfile: apache/dockerfile
    volumes:
      - ./src/:/srv/http/parking-system
    ports:
      - "80:80"

  php:
    container_name: php_8.2
    build:
      context: .devops
      dockerfile: php/dockerfile
    volumes:
      - ./src/:/srv/http/parking-system

  mysql:
    container_name: mysql_8.1
    image: mysql:8.1.0
    ports:
      - 3306:3306
    volumes:
      - ./.devops/mysql/my-local.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: parking_system
      MYSQL_USER: ps_backend_user
      MYSQL_PASSWORD: ps_backend_user_password

volumes:
  mysql: